name: Sync Developer Repo

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:     # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone developer repo
        run: |
          git clone --single-branch --branch main https://x-access-token:${{ secrets.DEVELOPER_REPO_PAT }}@github.com/sinchana-g/video-conferencing-chatbot.git developer-repo
          cd developer-repo
          git remote rename origin developer

      - name: Add your repo as target
        run: |
          cd developer-repo
          git remote add myrepo https://github.com/Gopalkrishna-Daisy/video-conferencing-chatbot.git

      - name: Push to your repo (force update)
        run: |
          cd developer-repo
          git push myrepo main --force

