name: Trigger Sync to My Repo on Push

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Push to my repo
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git remote add myrepo https://x-access-token:${{ secrets.YOUR_REPO_PAT }}@github.com/Gopalkrishna-Daisy/video-conferencing-chatbot.git
        git push myrepo main --force
